name: deploy-auth


on:
  push:
    branches:
      - main
      - master
    paths: 
      - 'auth/**'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
